create table public.meetings (
    id              bigint generated by default as identity primary key,
    club_id         uuid references public.clubs not null,
    reading_id      bigint references public.readings not null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    scheduled_for   timestamptz not null,
    section         text
);
comment on table public.meetings is 'All meetings for each club and reading.';
