create table public.members (
    id              bigint generated by default as identity primary key,
    user_id         uuid references auth.users on delete cascade not null,
    club_id         uuid references public.clubs not null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    display_name    text,
    unique (user_id, club_id)
);
comment on table public.members is 'All active members in each club.';
