create table public.readings (
    id              bigint generated by default as identity primary key,
    club_id         uuid references public.clubs not null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    title           text,
    reading_desc    text,
    supplements     jsonb
);
comment on table public.readings is 'All readings for each club.';
