-- Custom types
create type public.app_permission as enum (
    'reading.create',
    'reading.delete',
    'reading.update',
    'club.update',
    'schedule.update',
    'member.create',
    'member.delete',
    'members.create',
    'members.delete',
    'suggestion.create',
    'suggestion.delete',
    'suggestions.delete'
    );
create type public.app_role as enum ('admin', 'member');

-- USER ROLES
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- ROLE PERMISSIONS
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

-- DEFINE PERMISSIONS
insert into public.role_permissions (role, permission)
values
    ('admin', 'reading.create'),
    ('admin', 'reading.delete'),
    ('admin', 'reading.update'),
    ('admin', 'club.update'),
    ('admin', 'schedule.update'),
    ('admin', 'members.create'),
    ('admin', 'members.delete'),
    ('admin', 'suggestion.create'),
    ('admin', 'suggestion.delete'),
    ('admin', 'suggestions.delete'),
    ('member', 'member.delete'),
    ('member', 'suggestion.create'),
    ('member', 'suggestion.delete');
